# Método Iterativo de Gauss-Jacobi
## Objetivos
Os objetivos desse notebook são dois:

1. Implementar uma função que calcula a norma-infinito de dois vetores

2. Implementar o método de Gauss-Jacobi e testá-lo
 

## Implementação
Nós iremos implementar os algoritmos parte por parte, de acordo com as estratégias mostradas em sala. As instruções estão nos comentários nas funções abaixo. Você só precisa editar onde estiver indicado. 

Para executar uma célula, selecione a célula e pressione ```Ctrl + Enter```. Após implementar as funções abaixo, você deve executar cada uma das células, preferencialmente na ordem em que elas aparecem.


### Norma de vetores

Implemente a norma-$\infty$ para vetores conforme a equação abaixo:

$\frac{\max_{1\leq i\leq n}|v_i - x_i|}{\max_{1\leq i\leq n}|v_i|}$

* Crie duas variaveis uma para guardar o máximo do numerador e outra para guardar o máximo do denominador e as inicialize com zero.
 
* Depois percorra em um loop em i, os componentes de v e x, calculando a diferença de cada componente. Se |v[i]-x[i]| > máximo do numerador, atualize o máximo do numerador com esse valor. Da mesma forma se |v[i]| > máximo do denominador, atualize o máximo do denominador com esse valor.
 
* Por fim retorne o máximo do numerador dividido pelo máximo do denominador.

In [1]:
import numpy as np

In [2]:
def norma(v,x):
    """Calcula a norma entre dois vetores v e x.
    """
    n = len(v)
    if type(v) != np.ndarray:
        v = np.array(v)
    if type(x) != np.ndarray:
        x = np.array(x)
        
    maxDif = max(abs(v-x))
    maxV = max(abs(v))
    
    norma = maxDif/maxV 
    
    return norma

Agora precisamos testar se a função está implementada corretamente. Iremos usar o exemplo mostrado em sala.

$x^{(0)} = \left(\begin{array}{r}
0.7\\
-1.6\\
0.6\\
\end{array}\right)\ e\ x^{(1)}= \left(\begin{array}{r}
0.96\\
-1.86\\
0.94\\
\end{array}\right) $

In [3]:
## Defina x0 e x1, calcule a norma d e mostre o seu valor
# Escreva o seu código aqui
v = np.array([0.96,-1.86,0.94])
x = np.array([0.7,-1.6,0.6])
norma(v,x)

0.18279569892473116

In [4]:
0.34/1.86

0.1827956989247312

Se estiver tudo ok, ao executar a célula acima, você deve ver a resposta:
```
0.18279569892473116
```

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Método de Gauss-Jacobi

Iremos seguir a seguinte estratégia:

1. Crie os dois vetores x e v de tamanhos n com zeros (já foi feito abaixo).

2. Transforme o sistema Ax=b em x = Cx+g, transformando a matriz A diretamente na matriz C e o vetor b no vetor g conforme a equação abaixo:

$
\underbrace{\left[
\begin{array}{c}
x_1^{(k+1)}\\
x_2^{(k+1)}\\
x_3^{(k+1)}\\
\vdots\\
x_n^{(k+1)}\\
\end{array}
\right]}_{x^{(k+1)}} =
\underbrace{\left[
\begin{array}{ccccc}
0 & -\frac{a_{12}}{a_{11}} & -\frac{a_{13}}{a_{11}} & \dots & -\frac{a_{1n}}{a_{11}}\\ 
-\frac{a_{21}}{a_{22}} & 0 &-\frac{a_{23}}{a_{22}} & \dots & -\frac{a_{2n}}{a_{22}}\\
-\frac{a_{31}}{a_{33}} & -\frac{a_{32}}{a_{33}} & 0 &\dots & -\frac{a_{3n}}{a_{33}}\\
\vdots & \vdots & \vdots & \ddots & \vdots\\
-\frac{a_{n1}}{a_{nn}} & -\frac{a_{n2}}{a_{nn}} &\dots &-\frac{a_{n,n-1}}{a_{nn}} & 0 \\ 
\end{array}
\right]}_{C} \underbrace{\left[
\begin{array}{c}
x_1^{(k)}\\
x_2^{(k)}\\
x_3^{(k)}\\
\vdots\\
x_n^{(k)}\\
\end{array}
\right]}_{x^{(k)}} + \underbrace{\left[
\begin{array}{c}
\frac{b_1}{a_{11}}\\
\frac{b_2}{a_{22}}\\
\frac{b_3}{a_{33}}\\
\vdots\\
\frac{b_n}{a_{nn}}\\
\end{array}
\right]}_{g}
$

3.Inicializar o vetor x com a aproximação inicial $b_{i}/A_{ii}$.

4.Realizar as iterações em k. Para cada iteração k:

   * Calcula o vetor v com a aproximação atual (você precisa de dois loops)
   
   * Calcula a norma entre v e x, usando a função norma
   
   * Verifica o critério de parada. Se for atendido, retorna o vetor atual. Caso contrário, atualiza o vetor x e continua a próxima iteração. Para atualizar o vetor x, você usa slicing de listas ou usa um loop para percorrer o vetor inteiro (x = v não vai funcionar.)

In [12]:
def jacobi(A, b, epsilon, iterMax=50):
    """Resolve o sistema linear Ax=b usando o método iterativo Gauss-Jacobi.
    O critério de parada utiliza a norma-infinito.
    Saída é o vetor x.
    
    """
    if type(A) != np.ndarray:
        A = np.array(A).astype(float)
    if type(b) != np.ndarray:
        b = np.array(b).astype(float)
        
    n = len(A)
    #x = n * [0]
    x = np.zeros(n)
    #v = n * [0]
    v = np.zeros(n)
    
    for i in range(n):
        
        b[i] = b[i]/A[i][i]
        A[i] = -A[i]/A[i][i]      
        
        x[i] = b[i]
        
        A[i][i] = 0
        
    for k  in range(iterMax):
        for i in range(n):
            v[i] = b[i] + sum((A*x)[i]) #Podia ser np.dot(A,x)[i]
            
        if norma(v,x) <= epsilon :
            return v
        x = np.copy(v)
        
    print("Passou do limite de iterações")
    return v

**Não se esqueça de executar a célula de código acima!**

Agora precisamos testar se a função está implementada corretamente.
Teste com o exemplo visto em sala:

$\begin{cases} 
10x_1 +2x_2+x_3= 7\\
x_1+ 5x_2+x_3=-8\\
2x_1 + 3x_2 + 10x_3=6\\
\end{cases}
$

e com $\varepsilon = 0.05$. 

In [13]:
## Defina a matriz A, o vetor b e o epsilon.
## Depois chame a função jacobi e mostre o resultado obtido.
# Escreva o seu código aqui
A = np.array([[10,2,1],[1,5,1],[2,3,10]]).astype(float)
b = [7,-8,6]
epsilon = 0.05


jacobi(A,b,epsilon)

array([ 0.9994, -1.9888,  0.9984])

Se estiver tudo ok, ao executar a célula acima, você deve ver a resposta:
```
[0.9994, -1.9888000000000001, 0.9984]

```

### Exercício

Use a sua função para resolver o seguinte sistema linear:

$\begin{cases} 
10x_1 +3x_2-2x_3= 57\\
2x_1+ 8x_2-x_3=20\\
x_1 + x_2 + 5x_3=-4\\
\end{cases}
$

e com $\varepsilon = 0.01$. 

In [80]:
## Defina a matriz A, o vetor b e o epsilon.
## Depois chame a função jacobi e mostre o resultado obtido.
# Escreva o seu código aqui
A = np.array([[10,3,-2],[2,8,-1],[1,1,5]]).astype(float)
b = [57,20,-4]
epsilon = 0.01


jacobi(A,b,epsilon)

array([ 4.99552  ,  0.9995375, -2.00723  ])