# Método Iterativo de Gauss-Seidel
## Objetivos
O objetivo desse notebook é implementar o método de Gauss-Seidel e testá-lo.
 

## Implementação
Nós iremos implementar os algoritmos parte por parte, de acordo com as estratégias mostradas em sala. As instruções estão nos comentários nas funções abaixo. Você só precisa editar onde estiver indicado. 

Para executar uma célula, selecione a célula e pressione ```Ctrl + Enter```. Após implementar as funções abaixo, você deve executar cada uma das células, preferencialmente na ordem em que elas aparecem.


In [9]:
import numpy as np

### Norma de vetores

Iremos precisar da função norma implementada no notebook do Gauss-Jacobi. Copie e cole o código na célula abaixo.

In [10]:
def norma(v,x):
    """Calcula a norma entre dois vetores v e x.
    """
    n = len(v)
    if type(v) != np.ndarray:
        v = np.array(v)
    if type(x) != np.ndarray:
        x = np.array(x)
        
    maxDif = max(abs(v-x))
    maxV = max(abs(v))
    
    norma = maxDif/maxV 
    
    return norma

### Método de Gauss-Seidel

Tomando como base o método de Gauss-Jacobi, faça as seguintes alterações:

1. O vetor x **não** precisa ser inicializado com $b_i/a_{ii}$.

2. Altere na parte das iterações, de modo que o vetor x agora contém a aproximação atual e o vetor v contém a aproximação anterior. Assim, salve o valor anterior de x em v logo antes de receber o novo valor.

3. Altere a ordem de chamada dos parâmetros na função norma.

In [37]:
def seidel(A, b, epsilon, iterMax=50):
    """Resolve o sistema linear Ax=b usando o método iterativo Gauss-Jacobi.
    O critério de parada utiliza a norma-infinito.
    Saída é o vetor x.
    
    """
    if type(A) != np.ndarray:
        A = np.array(A).astype(float)
    if type(b) != np.ndarray:
        b = np.array(b).astype(float)
        
    n = len(A)
    #x = n * [0]
    x = np.zeros(n)
    #v = n * [0]
    v = np.zeros(n)
    
    for i in range(n):
        
        b[i] = b[i]/A[i][i]
        A[i] = -A[i]/A[i][i]      
        
        A[i][i] = 0
        
    for k  in range(iterMax):
        
        x = np.copy(v)
        for i in range(n):
            
            
            v[i] = b[i] + sum((A*v)[i]) #Podia ser np.dot(A,x)[i]
            
            
        if norma(v,x) < epsilon :
            return v
        
    print("Passou do limite de iterações")
    return v

In [38]:
print("\n#### GAUSS-SEIDEL ####")

A1 = [[4.0, -1.0, 0.0, 0.0],
     [-1.0, 4.0, -1.0, 0.0],
     [0.0, -1.0, 4.0, -1.0],
     [0.0, 0.0, -1.0, 4.0]]
b1 = [1.0, 1.0, 1.0, 1.0]
epsilon = 0.001

A1 = np.array(A1)
b1 = np.array(b1).astype(float)
 

y = seidel(A1, b1, epsilon)
print(y)


#### GAUSS-SEIDEL ####
[0.36358881 0.45451432 0.45453286 0.36363322]


**Não se esqueça de executar a célula de código acima!**

Agora precisamos testar se a função está implementada corretamente.
Teste com o exemplo visto em sala:

$\begin{cases} 
5x_1 +x_2+x_3= 5\\
3x_1+ 4x_2+x_3=6\\
3x_1 + 3x_2 + 6x_3=0\\
\end{cases}
$

com $\varepsilon = 0.05$. 

In [61]:
## Defina a matriz A, o vetor b e o epsilon.
## Depois chame a função seidel e mostre o resultado obtido.
# Escreva o seu código aqui
A = [[5,1,1],[3,4,1],[3,3,6]]
b = [5,6,0]
epsilon = 0.05

x = seidel(A,b,epsilon)
print(x)

[ 1.0075    0.99125  -0.999375]


Se estiver tudo ok, ao executar a célula acima, você deve ver a resposta:
```
[1.0075, 0.99125, -0.999375]

```

### Exercício

Use a sua função para resolver o seguinte sistema linear:

$\begin{cases} 
3x_1 \ \ \ +x_3= 3\\
x_1 - x_2 \ \ \ =20\\
3x_1 + x_2 + 2x_3=9\\
\end{cases}
$

e com $\varepsilon = 0.01$. 

In [5]:
## Defina a matriz A, o vetor b e o epsilon.
## Depois chame a função seidel e mostre o resultado obtido.
# Escreva o seu código aqui
A = [[3,0,1],[1,-1,0],[3,1,2]]
b = [3,20,9]
epsilon = 0.01

x = seidel(A,b,epsilon)
print(x)

[-11.17484631 -31.17484631  36.84969263]
